# -*- coding: utf-8 -*-
"""Grupo_3_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1AgvwrIoq1sjIQoJ-sTVYlkgsyT9Q-c
"""

import random
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
import numpy as np
import csv
import calendar
import os
from datetime import datetime, timedelta

#Cargar archivos
try:
    precios = pd.read_csv('precios.csv')
    civil_output = pd.read_csv('civil_output.csv')
    parametros = pd.read_csv('parametros.csv')
except FileNotFoundError as e:
    print(f"Error al cargar archivos: {e}")

 #Simular sensores
def simular_sensores():
    energia = float(np.random.normal(50, 10))
    vibracion = float(np.random.normal(3, 1))
    temperatura = float(np.random.normal(25, 5))

    energia = max(0.0, energia)
    vibracion = max(0.0, vibracion)

    return {
        'energia': round(energia, 2),
        'vibracion': round(vibracion, 2),
        'temperatura': round(temperatura, 2)
    }

#Detectar anomalias
def evaluar_anomalia(lecturas, limites):
    energia = lecturas['energia']
    vibracion = lecturas['vibracion']

    tipo = "Sin anomalía"
    clasificacion = "Normal"
    retraso = 0

    if energia > limites['limite_energia']:
        tipo = "Fallo eléctrico"
        clasificacion = "Crítico"
        retraso = 1
        return tipo, clasificacion, retraso

    if vibracion > limites['limite_vibracion']:
        tipo = "Riesgo estructural"
        clasificacion = "Crítico"
        retraso = 1
        return tipo, clasificacion, retraso

    if energia >= 0.9 * limites['limite_energia'] or vibracion >= 0.9 * limites['limite_vibracion']:
        tipo = "Valor alto"
        clasificacion = "Alerta"
        retraso = 1
        return tipo, clasificacion, retraso

    return tipo, clasificacion, retraso

#Calendario con retrasos

def crear_calendario_con_retrasos(civil_df, retrasos_por_actividad, fecha_inicio=None):

    if fecha_inicio is None:
        fecha_actual = datetime.today().date()
    else:
        fecha_actual = fecha_inicio

    calendario = []

    for idx, fila in civil_df.iterrows():
        actividad = fila['actividad']
        duracion_original = int(fila['duracion_dias'])
        retraso_total = retrasos_por_actividad.get(actividad, 0)

        duracion_final = duracion_original + retraso_total

        fecha_inicio_act = fecha_actual
        fecha_fin_act = fecha_inicio_act + timedelta(days=duracion_final - 1)

        calendario.append({
            "actividad": actividad,
            "inicio": fecha_inicio_act,
            "fin": fecha_fin_act,
            "duracion_original": duracion_original,
            "retraso": retraso_total,
            "duracion_final": duracion_final
        })

        fecha_actual = fecha_fin_act + timedelta(days=1)

    return calendario


#Simular el año completo
def simular_año_completo(civil_df, limites):

    datos_diarios = []
    retrasos_por_actividad = {}

    print("simulacion diaria\n")

    for idx, fila in civil_df.iterrows():
        actividad = fila['actividad']
        duracion = int(fila['duracion_dias'])

        print(f"Procesando: {actividad} ({duracion} días)")

        retraso_acumulado = 0

        for dia in range(1, duracion + 1):
            try:
                lecturas = simular_sensores()
                anomalia, clasificacion, retraso = evaluar_anomalia(lecturas, limites)
                retraso_acumulado += retraso

                datos_diarios.append({
                    'dia': dia,
                    'energia': lecturas['energia'],
                    'vibracion': lecturas['vibracion'],
                    'temperatura': lecturas['temperatura'],
                    'anomalia': anomalia,
                    'actividad': actividad,
                    'retraso': retraso
                })

                if anomalia != "Sin anomalía":
                    print(f"  Día {dia}: {anomalia} ({clasificacion}) - Retraso: {retraso} día(s)")

            except Exception as e:
                print(f"  ERROR en día {dia}: {e}")
                datos_diarios.append({
                    'dia': dia,
                    'energia': 0.0,
                    'vibracion': 0.0,
                    'temperatura': 0.0,
                    'anomalia': 'Error en lectura',
                    'actividad': actividad,
                    'retraso': 0
                })

        retrasos_por_actividad[actividad] = retraso_acumulado
        print(f"  Retraso total: {retraso_acumulado} día(s)\n")

    return datos_diarios, retrasos_por_actividad


#Crear archivo CSV
def crear_archivo_csv(datos_diarios, nombre_archivo='electronica_output.csv'):

    print(f" CREANDO ARCHIVO {nombre_archivo} ")

    try:
        # diagnóstico: mostrar directorio donde se guardará
        cwd = os.getcwd()
        ruta_absoluta = os.path.join(cwd, nombre_archivo)

        # convertir a DataFrame y guardar con pandas (más fiable)
        df = pd.DataFrame(datos_diarios)
        df.to_csv(ruta_absoluta, index=False, encoding='utf-8')

        print(f"[OK] Archivo guardado en: {ruta_absoluta}")
        print(f"[OK] Registros escritos: {len(df)}\n")
        return True

    except Exception as e:
        print(f"ERROR al crear archivo: {e}\n")
        return False



#Reporte de anomalias
def mostrar_reporte_anomalias(datos_diarios):

    print("=" * 60)
    print("REPORTE DE ANOMALÍAS DETECTADAS")
    print("=" * 60)

    total_dias = len(datos_diarios)
    anomalias_encontradas = [d for d in datos_diarios if d['anomalia'] != "Sin anomalía"]

    print(f"\nTotal de días simulados: {total_dias}")
    print(f"Total de anomalías: {len(anomalias_encontradas)}")
    print(f"Porcentaje de días con anomalías: {len(anomalias_encontradas)/total_dias*100:.2f}%\n")

    conteo_tipos = {}
    retraso_total = 0

    for anomalia in anomalias_encontradas:
        tipo = anomalia['anomalia']
        retraso_total += anomalia['retraso']
        conteo_tipos[tipo] = conteo_tipos.get(tipo, 0) + 1

    print("TIPOS DE ANOMALÍAS:")
    print("-" * 60)
    for tipo, cantidad in conteo_tipos.items():
        print(f"  • {tipo}: {cantidad} ocurrencias")

    print(f"\nRETRASO TOTAL ACUMULADO: {retraso_total} día(s)")
    print("=" * 60)
    print()

    if len(anomalias_encontradas) > 0:
        print("DETALLE DE PRIMERAS ANOMALÍAS:")
        print("-" * 60)
        for i, anom in enumerate(anomalias_encontradas[:10], 1):
            print(f"{i}. Día {anom['dia']} - {anom['actividad']}")
            print(f"   Tipo: {anom['anomalia']}")
            print(f"   Energía: {anom['energia']}, Vibración: {anom['vibracion']}")
            print(f"   Retraso: {anom['retraso']} día(s)\n")

#Modulo principal

def ejecutar_electronica(civil_df, limites):

    print("\n" + "="*60)
    print("INICIANDO MÓDULO DE ELECTRÓNICA")
    print("="*60 + "\n")

    datos_diarios, retrasos_por_actividad = simular_año_completo(civil_df, limites)

    crear_archivo_csv(datos_diarios)
    mostrar_reporte_anomalias(datos_diarios)

    calendario = crear_calendario_con_retrasos(civil_df, retrasos_por_actividad)

    print("CALENDARIO CON RETRASOS:")
    print("-" * 60)
    for item in calendario:
        print(f"{item['actividad']}")
        print(f"  Inicio: {item['inicio']}, Fin: {item['fin']}")
        print(f"  Duración original: {item['duracion_original']} días")
        print(f"  Retraso: {item['retraso']} días")
        print(f"  Duración final: {item['duracion_final']} días\n")

    return datos_diarios, retrasos_por_actividad, calendario

#Mostrar anomalias desde CSV

def mostrar_anomalias(archivo):
    try:
        df = pd.read_csv(archivo)
        posibles = [c for c in df.columns if "anom" in c.lower()]
        pd.set_option('display.max_rows', None)
        pd.set_option('display.max_columns', None)

        if not posibles:
            print("No se encontró una columna que indique anomalías en el archivo.")
            print("Columnas del archivo:", list(df.columns))
            return

        col_anom = posibles[0]

        # CORRECCIÓN: usar .str.lower() sobre la serie
        anomalias = df[df[col_anom].astype(str).str.lower() != "sin anomalía"]

        print("\n===== ANOMALÍAS DETECTADAS =====")
        if anomalias.empty:
            print("No se detectaron anomalías.")
        else:
            print(anomalias)

    except FileNotFoundError:
        print(f"No se encontró el archivo: {archivo}")


#Graficas

def graficar_parametros(datos_diarios):
    df = pd.DataFrame(datos_diarios)

    plt.figure(figsize=(10,4))
    plt.plot(df["dia"], df["energia"])
    plt.title("Energía diaria")
    plt.xlabel("Día")
    plt.ylabel("Energía")
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(10,4))
    plt.plot(df["dia"], df["vibracion"])
    plt.title("Vibración diaria")
    plt.xlabel("Día")
    plt.ylabel("Vibración")
    plt.grid(True)
    plt.show()

    plt.figure(figsize=(10,4))
    plt.plot(df["dia"], df["temperatura"])
    plt.title("Temperatura diaria")
    plt.xlabel("Día")
    plt.ylabel("Temperatura")
    plt.grid(True)
    plt.show()


def graficar_gantt(calendario):
    df = pd.DataFrame(calendario)

    df["inicio"] = pd.to_datetime(df["inicio"])
    df["fin"] = pd.to_datetime(df["fin"])

    plt.figure(figsize=(12,8))

    for i, fila in df.iterrows():
        inicio = fila["inicio"]
        duracion = (fila["fin"] - fila["inicio"]).days + 1
        color = "red" if fila["retraso"] > 0 else "green"

        plt.barh(
            fila["actividad"],
            duracion,
            left=inicio,
            color=color
        )

    plt.xlabel("Fecha")
    plt.ylabel("Actividad")
    plt.title("Diagrama de Gantt con retrasos")

    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gcf().autofmt_xdate()

    plt.tight_layout()
    plt.show()


def generar_graficos(datos_diarios, calendario):
    print("Generando Gráficas")
    graficar_parametros(datos_diarios)
    graficar_gantt(calendario)


if __name__ == "__main__":

    #Crear diccionario de límites desde parametros.csv
    limites = {
        "limite_energia": float(parametros.loc[0, "limite_energia"]),
        "limite_vibracion": float(parametros.loc[0, "limite_vibracion"])
    }

    #Ejecutar la simulación
    datos_diarios, retrasos_por_actividad, calendario = ejecutar_electronica(
        civil_output, limites
    )

    generar_graficos(datos_diarios, calendario)

    # mostrar las anomalías leyendo el archivo creado
    mostrar_anomalias("electronica_output.csv")